//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neydarsimi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tulkur
    {
        public int id { get; set; }
        public string nafn { get; set; }
        public Nullable<int> kt { get; set; }
    }
}
