//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neydarsimi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vinna
    {
        public int nr { get; set; }
        public string kt { get; set; }
        public int turn_off { get; set; }
    
        public virtual Neydarsimi1 Neydarsimi1 { get; set; }
        public virtual Tulkur Tulkur { get; set; }
    }
}
